/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Messages_CONSTANTS_H
#define Messages_CONSTANTS_H

#include "Messages_types.h"



class MessagesConstants {
 public:
  MessagesConstants();

};

extern const MessagesConstants g_Messages_constants;



#endif
