/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Messages_constants.h"



const MessagesConstants g_Messages_constants;

MessagesConstants::MessagesConstants() {
}



