/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MessageService_H
#define MessageService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "Messages_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MessageServiceIf {
 public:
  virtual ~MessageServiceIf() {}
  virtual void SendMessage(const ReqInfo& msg) = 0;
  virtual void SendAndRecMessage(ResultInfo& _return, const ReqInfo& msg) = 0;
  virtual void SendPacket(const BaseSKB& msg) = 0;
  virtual void SendAndRecPacket(ResultInfo& _return, const BaseSKB& msg) = 0;
};

class MessageServiceIfFactory {
 public:
  typedef MessageServiceIf Handler;

  virtual ~MessageServiceIfFactory() {}

  virtual MessageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MessageServiceIf* /* handler */) = 0;
};

class MessageServiceIfSingletonFactory : virtual public MessageServiceIfFactory {
 public:
  MessageServiceIfSingletonFactory(const boost::shared_ptr<MessageServiceIf>& iface) : iface_(iface) {}
  virtual ~MessageServiceIfSingletonFactory() {}

  virtual MessageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MessageServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<MessageServiceIf> iface_;
};

class MessageServiceNull : virtual public MessageServiceIf {
 public:
  virtual ~MessageServiceNull() {}
  void SendMessage(const ReqInfo& /* msg */) {
    return;
  }
  void SendAndRecMessage(ResultInfo& /* _return */, const ReqInfo& /* msg */) {
    return;
  }
  void SendPacket(const BaseSKB& /* msg */) {
    return;
  }
  void SendAndRecPacket(ResultInfo& /* _return */, const BaseSKB& /* msg */) {
    return;
  }
};

typedef struct _MessageService_SendMessage_args__isset {
  _MessageService_SendMessage_args__isset() : msg(false) {}
  bool msg :1;
} _MessageService_SendMessage_args__isset;

class MessageService_SendMessage_args {
 public:

  MessageService_SendMessage_args(const MessageService_SendMessage_args&);
  MessageService_SendMessage_args& operator=(const MessageService_SendMessage_args&);
  MessageService_SendMessage_args() {
  }

  virtual ~MessageService_SendMessage_args() throw();
  ReqInfo msg;

  _MessageService_SendMessage_args__isset __isset;

  void __set_msg(const ReqInfo& val);

  bool operator == (const MessageService_SendMessage_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const MessageService_SendMessage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageService_SendMessage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MessageService_SendMessage_pargs {
 public:


  virtual ~MessageService_SendMessage_pargs() throw();
  const ReqInfo* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageService_SendAndRecMessage_args__isset {
  _MessageService_SendAndRecMessage_args__isset() : msg(false) {}
  bool msg :1;
} _MessageService_SendAndRecMessage_args__isset;

class MessageService_SendAndRecMessage_args {
 public:

  MessageService_SendAndRecMessage_args(const MessageService_SendAndRecMessage_args&);
  MessageService_SendAndRecMessage_args& operator=(const MessageService_SendAndRecMessage_args&);
  MessageService_SendAndRecMessage_args() {
  }

  virtual ~MessageService_SendAndRecMessage_args() throw();
  ReqInfo msg;

  _MessageService_SendAndRecMessage_args__isset __isset;

  void __set_msg(const ReqInfo& val);

  bool operator == (const MessageService_SendAndRecMessage_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const MessageService_SendAndRecMessage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageService_SendAndRecMessage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MessageService_SendAndRecMessage_pargs {
 public:


  virtual ~MessageService_SendAndRecMessage_pargs() throw();
  const ReqInfo* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageService_SendAndRecMessage_result__isset {
  _MessageService_SendAndRecMessage_result__isset() : success(false) {}
  bool success :1;
} _MessageService_SendAndRecMessage_result__isset;

class MessageService_SendAndRecMessage_result {
 public:

  MessageService_SendAndRecMessage_result(const MessageService_SendAndRecMessage_result&);
  MessageService_SendAndRecMessage_result& operator=(const MessageService_SendAndRecMessage_result&);
  MessageService_SendAndRecMessage_result() {
  }

  virtual ~MessageService_SendAndRecMessage_result() throw();
  ResultInfo success;

  _MessageService_SendAndRecMessage_result__isset __isset;

  void __set_success(const ResultInfo& val);

  bool operator == (const MessageService_SendAndRecMessage_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MessageService_SendAndRecMessage_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageService_SendAndRecMessage_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageService_SendAndRecMessage_presult__isset {
  _MessageService_SendAndRecMessage_presult__isset() : success(false) {}
  bool success :1;
} _MessageService_SendAndRecMessage_presult__isset;

class MessageService_SendAndRecMessage_presult {
 public:


  virtual ~MessageService_SendAndRecMessage_presult() throw();
  ResultInfo* success;

  _MessageService_SendAndRecMessage_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MessageService_SendPacket_args__isset {
  _MessageService_SendPacket_args__isset() : msg(false) {}
  bool msg :1;
} _MessageService_SendPacket_args__isset;

class MessageService_SendPacket_args {
 public:

  MessageService_SendPacket_args(const MessageService_SendPacket_args&);
  MessageService_SendPacket_args& operator=(const MessageService_SendPacket_args&);
  MessageService_SendPacket_args() {
  }

  virtual ~MessageService_SendPacket_args() throw();
  BaseSKB msg;

  _MessageService_SendPacket_args__isset __isset;

  void __set_msg(const BaseSKB& val);

  bool operator == (const MessageService_SendPacket_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const MessageService_SendPacket_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageService_SendPacket_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MessageService_SendPacket_pargs {
 public:


  virtual ~MessageService_SendPacket_pargs() throw();
  const BaseSKB* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageService_SendAndRecPacket_args__isset {
  _MessageService_SendAndRecPacket_args__isset() : msg(false) {}
  bool msg :1;
} _MessageService_SendAndRecPacket_args__isset;

class MessageService_SendAndRecPacket_args {
 public:

  MessageService_SendAndRecPacket_args(const MessageService_SendAndRecPacket_args&);
  MessageService_SendAndRecPacket_args& operator=(const MessageService_SendAndRecPacket_args&);
  MessageService_SendAndRecPacket_args() {
  }

  virtual ~MessageService_SendAndRecPacket_args() throw();
  BaseSKB msg;

  _MessageService_SendAndRecPacket_args__isset __isset;

  void __set_msg(const BaseSKB& val);

  bool operator == (const MessageService_SendAndRecPacket_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const MessageService_SendAndRecPacket_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageService_SendAndRecPacket_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MessageService_SendAndRecPacket_pargs {
 public:


  virtual ~MessageService_SendAndRecPacket_pargs() throw();
  const BaseSKB* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageService_SendAndRecPacket_result__isset {
  _MessageService_SendAndRecPacket_result__isset() : success(false) {}
  bool success :1;
} _MessageService_SendAndRecPacket_result__isset;

class MessageService_SendAndRecPacket_result {
 public:

  MessageService_SendAndRecPacket_result(const MessageService_SendAndRecPacket_result&);
  MessageService_SendAndRecPacket_result& operator=(const MessageService_SendAndRecPacket_result&);
  MessageService_SendAndRecPacket_result() {
  }

  virtual ~MessageService_SendAndRecPacket_result() throw();
  ResultInfo success;

  _MessageService_SendAndRecPacket_result__isset __isset;

  void __set_success(const ResultInfo& val);

  bool operator == (const MessageService_SendAndRecPacket_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MessageService_SendAndRecPacket_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageService_SendAndRecPacket_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageService_SendAndRecPacket_presult__isset {
  _MessageService_SendAndRecPacket_presult__isset() : success(false) {}
  bool success :1;
} _MessageService_SendAndRecPacket_presult__isset;

class MessageService_SendAndRecPacket_presult {
 public:


  virtual ~MessageService_SendAndRecPacket_presult() throw();
  ResultInfo* success;

  _MessageService_SendAndRecPacket_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MessageServiceClient : virtual public MessageServiceIf {
 public:
  MessageServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void SendMessage(const ReqInfo& msg);
  void send_SendMessage(const ReqInfo& msg);
  void SendAndRecMessage(ResultInfo& _return, const ReqInfo& msg);
  void send_SendAndRecMessage(const ReqInfo& msg);
  void recv_SendAndRecMessage(ResultInfo& _return);
  void SendPacket(const BaseSKB& msg);
  void send_SendPacket(const BaseSKB& msg);
  void SendAndRecPacket(ResultInfo& _return, const BaseSKB& msg);
  void send_SendAndRecPacket(const BaseSKB& msg);
  void recv_SendAndRecPacket(ResultInfo& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MessageServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MessageServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MessageServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_SendMessage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_SendAndRecMessage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_SendPacket(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_SendAndRecPacket(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MessageServiceProcessor(boost::shared_ptr<MessageServiceIf> iface) :
    iface_(iface) {
    processMap_["SendMessage"] = &MessageServiceProcessor::process_SendMessage;
    processMap_["SendAndRecMessage"] = &MessageServiceProcessor::process_SendAndRecMessage;
    processMap_["SendPacket"] = &MessageServiceProcessor::process_SendPacket;
    processMap_["SendAndRecPacket"] = &MessageServiceProcessor::process_SendAndRecPacket;
  }

  virtual ~MessageServiceProcessor() {}
};

class MessageServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MessageServiceProcessorFactory(const ::boost::shared_ptr< MessageServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MessageServiceIfFactory > handlerFactory_;
};

class MessageServiceMultiface : virtual public MessageServiceIf {
 public:
  MessageServiceMultiface(std::vector<boost::shared_ptr<MessageServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MessageServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MessageServiceIf> > ifaces_;
  MessageServiceMultiface() {}
  void add(boost::shared_ptr<MessageServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void SendMessage(const ReqInfo& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->SendMessage(msg);
    }
    ifaces_[i]->SendMessage(msg);
  }

  void SendAndRecMessage(ResultInfo& _return, const ReqInfo& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->SendAndRecMessage(_return, msg);
    }
    ifaces_[i]->SendAndRecMessage(_return, msg);
    return;
  }

  void SendPacket(const BaseSKB& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->SendPacket(msg);
    }
    ifaces_[i]->SendPacket(msg);
  }

  void SendAndRecPacket(ResultInfo& _return, const BaseSKB& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->SendAndRecPacket(_return, msg);
    }
    ifaces_[i]->SendAndRecPacket(_return, msg);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MessageServiceConcurrentClient : virtual public MessageServiceIf {
 public:
  MessageServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void SendMessage(const ReqInfo& msg);
  void send_SendMessage(const ReqInfo& msg);
  void SendAndRecMessage(ResultInfo& _return, const ReqInfo& msg);
  int32_t send_SendAndRecMessage(const ReqInfo& msg);
  void recv_SendAndRecMessage(ResultInfo& _return, const int32_t seqid);
  void SendPacket(const BaseSKB& msg);
  void send_SendPacket(const BaseSKB& msg);
  void SendAndRecPacket(ResultInfo& _return, const BaseSKB& msg);
  int32_t send_SendAndRecPacket(const BaseSKB& msg);
  void recv_SendAndRecPacket(ResultInfo& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
